AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Various APIs for interfacing with Assets Collection
  Test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
  Api:
    # enable CORS; to make more specific, change the origin wildcard
    # to a particular domain name, e.g. "'www.example.com'"
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  AssetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Policies:
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Events:
        Assets:
          Type: Api
          Properties:
            Path: /assets
            Method: ANY
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./nodejs
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AssetsApi:
    Description: "API Gateway endpoint URL for Prod stage for Assets function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/assets/"
  AssetsFunction:
    Description: "Assets Lambda Function ARN"
    Value: !GetAtt AssetsFunction.Arn
  AssetsFunctionIamRole:
    Description: "Implicit IAM Role created for Assets function"
    Value: !GetAtt AssetsFunctionRole.Arn
